### ISSUE TITLE
formula and description are not consistent

### ISSUE THREAD

**Issue by xihan1** [erfangc/bdozer#14]
ProfitLoss - NetIncomeLossAttributableToNoncontrollingInterest

From the tool, no easy way to know what are ProfitLoss and NetIncomeLossAttributableToNoncontrollingInterest except by guessing from the description.

**Comment by erfangc** [comment]
each Item have a `Name` and a `Description` where the description is long-form .. let me add both of them to the Item editor

(its now available in the URL as well but that is kind of hidden)
