### ISSUE TITLE
the sign of the number appears wrong

### ISSUE THREAD

**Issue by xihan1** [erfangc/bdozer#24]
for stock SAVE
<img width="1000" alt="Screen Shot 2021-04-11 at 00 56 58" src="https://user-images.githubusercontent.com/38635487/114293041-db32a780-9a60-11eb-80a8-fd7435695d93.png">
<img width="1760" alt="Screen Shot 2021-04-11 at 01 01 13" src="https://user-images.githubusercontent.com/38635487/114293109-7035a080-9a61-11eb-8d06-726b3bf47b5a.png">

**Comment by erfangc** [comment]
That is interesting, let me see how that happened

**Comment by erfangc** [comment]
when you click into the fact it shows up as negative

![image](https://user-images.githubusercontent.com/6001694/114399783-4d91ad80-9b6f-11eb-933c-fcc1feb9961c.png)

**Comment by erfangc** [comment]
@xihan1 the raw number in the report is negative, however the "sign" attribute is also "negative" ... in this case I am not sure if the calculation requires a negation or not. Does the numbers seem to add up? if you just followed the arithmetic laid out in the formulas for the subtotal lines?

**Comment by xihan1** [comment]
If you flip the sign, it will add up. I see where the confusion is coming from. I propose two approaches below. let me know what way makes more sense.

1. We make all the calculations to be additions and flip the sign of the raw number accordingly. 
2. Keep the sign of the raw number as it is but show the calculation as part of the tool. In this case, everything else will have a positive sign in the tool but a negative one for this item.
