### ISSUE TITLE
Compound growth always show 1%

### ISSUE THREAD

**Issue by xihan1** [erfangc/bdozer#32]
The compound growth item type always shows 1% after reopening the tab, although I put other numbers like 5 or 10
<img width="633" alt="Screen Shot 2021-04-13 at 13 53 38" src="https://user-images.githubusercontent.com/38635487/114598226-a93b6400-9c5f-11eb-9d9c-c287cf38cbe9.png">

**Comment by erfangc** [comment]
Will take a look
